name: Backend (Supabase) – Migrate & Deploy Functions

on:
  push:
    branches: [ main ]
    paths:
      - "supabase/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}   # PAT sbp_...
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}     # heaztitsbnotkozmhubw
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}     # DB password
      DENO_TLS_CA_STORE: system

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: 2.39.2  # no "v" prefix

      - name: Validate PAT shape
        run: |
          [[ "$SUPABASE_ACCESS_TOKEN" =~ ^sbp_ ]] || { echo "Not a PAT (sbp_*)"; exit 1; }
          echo "PAT OK"

      - name: Login
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Link (non-interactive)
        run: supabase link --project-ref "$SUPABASE_PROJECT_REF" --password "$SUPABASE_DB_PASSWORD"

      - name: Push migrations (auto-confirm)
        run: yes | supabase db push

      - name: Set function secrets (avoid SUPABASE_* names)
        run: |
          supabase secrets set \
            NEWS_SUPABASE_URL="https://${SUPABASE_PROJECT_REF}.supabase.co" \
            NEWS_SERVICE_ROLE_KEY="${{ secrets.NEWS_SERVICE_ROLE_KEY }}"

      - name: Deploy ingestnews
        run: supabase functions deploy ingestnews

      - name: List functions
        run: supabase functions list

      - name: Tail logs (brief)
        run: timeout 45s supabase functions logs ingestnews --tail || true
