name: Deploy ingestnews

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "supabase/functions/ingestnews/**"
      - "supabase/config.toml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: v2.39.2

      - name: Login
        run: supabase login --token "${SUPABASE_ACCESS_TOKEN}"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link
        run: supabase link --project-ref "${SUPABASE_PROJECT_REF}"
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

      - name: Set runtime secrets
        run: |
          supabase secrets set \
            NEWS_SUPABASE_URL="${NEWS_SUPABASE_URL}" \
            NEWS_SERVICE_ROLE_KEY="${NEWS_SERVICE_ROLE_KEY}"
        env:
          NEWS_SUPABASE_URL: ${{ secrets.NEWS_SUPABASE_URL }}
          NEWS_SERVICE_ROLE_KEY: ${{ secrets.NEWS_SERVICE_ROLE_KEY }}

      - name: Deploy function
        run: supabase functions deploy ingestnews

      - name: List functions
        run: supabase functions list
